# Generated by Django 5.1.3 on 2024-12-08 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_customersupport_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsel_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('appointment', '예약됨'), ('complete', '완료'), ('waiting', '대기 중')], default='waiting', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
