# Generated by Django 5.1.3 on 2024-12-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
