# Generated by Django 5.1.3 on 2024-12-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_login_pw_person_password_person_groups_and_more"),
        ("diary", "0002_diary_emotion_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="diary",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="diary",
            constraint=models.UniqueConstraint(
                fields=("user", "diary_date"), name="unique_diary_per_day"
            ),
        ),
    ]
