# Generated by Django 5.1.3 on 2024-12-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_diary_content_diary_title_diary_unique_diary_per_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="diary_write_date",
        ),
    ]
