# Generated by Django 5.1.3 on 2024-12-01 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_remove_diary_diary_write_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="diary_write_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
