# Generated by Django 5.1.3 on 2024-12-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0006_rename_fear_score_emotionanalysis_anxiety_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="diary_write_date",
            field=models.DateField(auto_now=True),
        ),
    ]
