# Generated by Django 5.1.3 on 2024-12-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0007_alter_diary_diary_write_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emotionanalysis",
            name="reason",
        ),
    ]
