# Generated by Django 5.1.3 on 2024-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="post_comment_content",
            field=models.TextField(default="Default comment"),
        ),
    ]
