# Generated by Django 5.1.3 on 2024-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_postcomment_post_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="post_comment_content",
            field=models.TextField(),
        ),
    ]
