# Generated by Django 5.1.3 on 2024-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_postcomment_post_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_title",
            field=models.CharField(default="", max_length=40),
        ),
    ]
