# Generated by Django 5.1.3 on 2024-12-01 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_remove_post_post_write_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_write_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="post_comment_write_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
