# Generated by Django 5.1.3 on 2024-12-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_alter_post_post_write_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_write_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="post_comment_write_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
