# Generated by Django 5.1.3 on 2024-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_alter_post_post_write_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
