# Generated by Django 5.1.3 on 2024-11-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=15)),
                ("login_id", models.CharField(max_length=15, unique=True)),
                ("login_pw", models.CharField(max_length=15)),
                ("phone_num", models.CharField(blank=True, max_length=15, null=True)),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("counselor", "Counselor"),
                            ("customer_support", "Customer Support"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.person",
                    ),
                ),
                (
                    "gender",
                    models.CharField(choices=[("M", "남"), ("F", "여")], max_length=1),
                ),
                ("birth", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Counselor",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        limit_choices_to={"role": "counselor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.person",
                    ),
                ),
                (
                    "gender",
                    models.CharField(choices=[("M", "남"), ("F", "여")], max_length=1),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counselors",
                        to="accounts.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerSupport",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.person",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_supports",
                        to="accounts.person",
                    ),
                ),
            ],
        ),
    ]
