# Generated by Django 5.1.3 on 2024-11-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_person_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="login_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="login_pw",
            field=models.CharField(max_length=20),
        ),
    ]
