# Generated by Django 5.1.3 on 2024-12-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_login_pw_person_password_person_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
