# Generated by Django 5.1.3 on 2024-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsel',
            name='is_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
