# Generated by Django 5.1.3 on 2024-12-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_login_pw_person_password_person_groups_and_more'),
        ('counsel', '0003_counsel_counsel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='customer_support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_support_counsels', to='accounts.customersupport'),
        ),
    ]
