# Generated by Django 5.1.3 on 2024-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0004_alter_counsel_customer_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsel',
            name='counsel_date',
        ),
        migrations.AddField(
            model_name='counsel',
            name='counsel_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
